package core

import eng "../engine"

MAX_MESSAGES :: eng.ENGINE_MAX_MESSAGES
MAX_MSG_LEN :: eng.ENGINE_MAX_MESSAGE_LEN


DEATH_CAUSE_MAX_LEN :: 128

MAX_SEEN_CONVS :: 64
MAX_DLG_FLAGS :: 32
MAX_CONV_ID_LEN :: 64
MAX_FLAG_LEN :: 64
