package core

MAX_INVENTORY :: 9
DMAP_UNREACHABLE :: 9999

BASE_ACTION_COST :: 1000
BASE_MOVE_COST :: 1000
BASE_AP_PER_ROUND :: 1000
MAX_DEPTH :: 12

LIGHT_DRAIN_INTERVAL :: 30
LIGHT_DRAIN_MIN :: 2
LIGHT_DRAIN_START_DEPTH :: 3

GAS_VENT_DAMAGE :: 3
GAS_VENT_POISON_TURNS :: 5
FIRE_VENT_DAMAGE :: 2
FIRE_VENT_BURNING_TURNS :: 4
FOUNTAIN_HEAL :: 5
WEB_STUCK_TURNS :: 3
DEFAULT_ENEMY_DETECTION_RADIUS :: 10
DEFAULT_ENEMY_MEMORY_TURNS :: 8

MIN_LIGHT_RADIUS_DEFAULT :: 3
MIN_LIGHT_RADIUS_DEEP :: 2
MIN_LIGHT_DEPTH :: 8

DURABILITY_WARN_THRESHOLD :: 5

// ─── Floor events ─────────────────────────────────────────────────────────────
EVENT_SPAWN_CHANCE :: 40 // percent chance per floor (depth >= 2)
EVENT_MIN_DEPTH :: 2 // no events on depth 1

SHRINE_HP_COST_PERCENT :: 30 // % of current HP sacrificed
SHRINE_BUFF_MAX_HP :: 5
SHRINE_BUFF_ATTACK :: 2
SHRINE_BUFF_LIGHT :: 2

CHEST_TRAP_CHANCE :: 40 // percent chance of trap
CHEST_TRAP_DAMAGE :: 5
CHEST_TRAP_POISON_TURNS :: 3

// ─── Surface town ─────────────────────────────────────────────────────────────
SURFACE_DEPTH :: 0
SURFACE_LIGHT_RADIUS :: 14 // town is daylit; see the whole hub
