package core

TILE_SIZE :: 32
SPRITE_SIZE :: 16
SCREEN_WIDTH :: 1280
SCREEN_HEIGHT :: 900
MAP_WIDTH :: 80
MAP_HEIGHT :: 50

SIDEBAR_WIDTH :: 256
MSG_REGION_HEIGHT :: 130
MAP_VIEW_WIDTH :: SCREEN_WIDTH - SIDEBAR_WIDTH
MAP_VIEW_HEIGHT :: SCREEN_HEIGHT - MSG_REGION_HEIGHT
